### ISSUE TITLE
SLSA: Merge av dp-track (NAIS:console)

### ISSUE THREAD

**Issue by Muni10** [nais/dependencytrack#21]
Vurdere om vi skal underlette for informasjons flyt i NAIS:console og bare ha en backend av depdendency track i management, utvikler trenger ikke direkte se dp-track frontend, med mindre vi linker til graf eller annet

**Comment by ybelMekk** [comment]
Må også se på resync i picante av images

**Comment by ybelMekk** [comment]
Done, deleting the rest in legacy and tenant
