### ISSUE TITLE
high load due to massive updates on DEPENDENCYMETRICS and VULNERABILITY

### ISSUE THREAD

**Issue by jw1u1** [nais/dependencytrack#74]
dependencymetrics receives updates one on each line per hour statistically:
`UPDATE "DEPENDENCYMETRICS" SET "LAST_OCCURRENCE"=$1 WHERE "ID"=$2

select relname,n_tup_ins,n_tup_upd,n_live_tup,autovacuum_count from pg_stat_user_tables order by n_tup_upd/n_live_tup desc;
-[ RECORD 1 ]----+-----------------------------------
relname          | DEPENDENCYMETRICS
n_tup_ins       | 186982
n_tup_upd      | 632665605
n_live_tup       | 331487
autovacuum_count | 11352`
 
 An impressing autovacuum_count.
 Please reduce the amount of updates. The Database is a persistence layer and not a logfile.

![image](https://github.com/user-attachments/assets/34851bbf-339a-412d-904a-800005cf2b7d)

Thousands of single-column updates on VULNERABILITY with the same amount on different columns.
Please consolidate them to multi-column updates

**Comment by ybelMekk** [comment]
hello, thanks for opening the issue, but i feel this fits better in the original project: https://github.com/DependencyTrack/dependency-track/issues

This is manly a helmcharts with some tweaks, but no tweaks in the "original" code.

**Comment by jw1u1** [comment]
Done: https://github.com/DependencyTrack/dependency-track/issues/4036

**Comment by jw1u1** [comment]
close
